import { Route, BnBListing, BookingRequest, Client } from '@/types';

export const INITIAL_ROUTES: Route[] = [
  {
    id: 'route-wil-uka',
    originName: 'Nairobi Wilson',
    originCode: 'WIL',
    destName: 'Diani Beach / Ukunda',
    destCode: 'UKA',
    carriers: ['Safarilink', 'Skyward Express', 'AirKenya'],
    aircraftType: 'Dash 8-300 / Cessna Grand Caravan',
    estimatedDuration: '1h 10m',
    basePriceKES: 13500,
    basePriceUSD: 105,
    description: 'Fly directly onto the pristine South Coast white sands without Mombasa traffic ferries.',
    featured: true,
    frequency: '4 daily flights',
  },
  {
    id: 'route-wil-lau',
    originName: 'Nairobi Wilson',
    originCode: 'WIL',
    destName: 'Lamu Island (Manda Airstrip)',
    destCode: 'LAU',
    carriers: ['Safarilink', 'Skyward Express', 'Fly540'],
    aircraftType: 'Dash 8-200 / Dash 8-300',
    estimatedDuration: '1h 20m',
    basePriceKES: 16500,
    basePriceUSD: 128,
    description: 'Direct flight to UNESCO heritage Lamu Archipelago. Step right into your waiting Swahili dhow.',
    featured: true,
    frequency: '3 daily flights',
  },
  {
    id: 'route-nbo-mba',
    originName: 'Nairobi JKIA',
    originCode: 'NBO',
    destName: 'Mombasa (Moi Intl)',
    destCode: 'MBA',
    carriers: ['Kenya Airways (Pride of Africa)', 'Jambojet'],
    aircraftType: 'Boeing 737-800 / Dash 8 Q400',
    estimatedDuration: '50 mins',
    basePriceKES: 9800,
    basePriceUSD: 76,
    description: 'Express jet service between Kenya’s capital and historical coastal hub.',
    featured: true,
    frequency: '12 daily flights',
  },
  {
    id: 'route-wil-mre',
    originName: 'Nairobi Wilson',
    originCode: 'WIL',
    destName: 'Maasai Mara (Keekorok / Serena)',
    destCode: 'MRE',
    carriers: ['Safarilink', 'AirKenya', 'Governors Aviation'],
    aircraftType: 'Cessna Grand Caravan EX / Twin Otter',
    estimatedDuration: '45 mins',
    basePriceKES: 24500,
    basePriceUSD: 190,
    description: 'Scenic low-altitude bush flight touching down right next to the Great Migration plains.',
    featured: true,
    frequency: '6 daily flights',
  },
  {
    id: 'route-nbo-myd',
    originName: 'Nairobi JKIA / Wilson',
    originCode: 'NBO',
    destName: 'Malindi / Watamu',
    destCode: 'MYD',
    carriers: ['Jambojet', 'Safarilink', 'Fly540'],
    aircraftType: 'Dash 8 Q400',
    estimatedDuration: '1h 05m',
    basePriceKES: 12500,
    basePriceUSD: 97,
    description: 'Gateway to Watamu Marine Park, Che Shale golden sand dunes, and pristine coral reefs.',
    featured: true,
    frequency: '3 daily flights',
  },
  {
    id: 'route-nbo-kis',
    originName: 'Nairobi JKIA',
    originCode: 'NBO',
    destName: 'Kisumu (Lake Victoria)',
    destCode: 'KIS',
    carriers: ['Kenya Airways', 'Jambojet', '748 Air Services'],
    aircraftType: 'Embraer 190 / Dash 8 Q400',
    estimatedDuration: '45 mins',
    basePriceKES: 8500,
    basePriceUSD: 66,
    description: 'Quick commuter connection across the Great Rift Valley to western lakeside city.',
    featured: false,
    frequency: '5 daily flights',
  },
];

export const INITIAL_STAYS: BnBListing[] = [
  {
    id: 'stay-diani-sultan',
    title: 'Sultan Sands Oceanfront Villa & Infinity Pool',
    slug: 'sultan-sands-diani-villa',
    location: 'Galu Beach, Diani, Kwale County',
    region: 'Coast',
    description: 'Exclusive 4-bedroom Swahili-Moorish private beachfront estate with personal chef, infinity lap pool overlooking turquoise Indian Ocean, and direct private beach access. Ideal for families and VIP retreats.',
    tagline: 'Private Oceanfront Haven with Dedicated Butler & Chef',
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    ],
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 8,
    amenities: ['Private Chef Included', 'Oceanview Infinity Pool', 'Starlink 250Mbps WiFi', 'Air Conditioning', 'Airport Chauffeur', 'Direct Beach Access'],
    pricePerNightKES: 65000,
    pricePerNightUSD: 500,
    ownerName: 'Capt. Tariq Al-Mandhry',
    ownerPhone: '+254722891200',
    active: true,
    featured: true,
    badge: 'Ultra-Luxury Top Pick',
  },
  {
    id: 'stay-lamu-shela-palace',
    title: 'Forodhani Swahili Heritage House',
    slug: 'forodhani-swahili-house-lamu',
    location: 'Shela Village Beachfront, Lamu Island',
    region: 'Coast',
    description: 'Masterpiece of authentic 18th-century Swahili stone architecture on Shela waterfront. Features ornate coral plasterwork, breezy rooftop terraces with 270-degree dhow channel panoramas, private plunge pool, and a team of 5 staff (cook, butler, captain).',
    tagline: 'Timeless Swahili Elegance on Shela Waterfront',
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
    ],
    bedrooms: 5,
    bathrooms: 5,
    maxGuests: 10,
    amenities: ['Full 5-Person House Staff', 'Private Dhow Boat Charter', 'Rooftop Sundowner Bar', 'Air-Conditioned Suites', 'Courtyard Plunge Pool'],
    pricePerNightKES: 85000,
    pricePerNightUSD: 660,
    ownerName: 'Fatma Bwana',
    ownerPhone: '+254711456789',
    active: true,
    featured: true,
    badge: 'Iconic Heritage',
  },
  {
    id: 'stay-karen-glasshouse',
    title: 'The Forest Pavilion & Botanical Cottage',
    slug: 'karen-forest-pavilion-nairobi',
    location: 'Miotoni Forest, Karen, Nairobi',
    region: 'Nairobi',
    description: 'Secluded glass & timber architectural sanctuary nestled in 3 acres of indigenous Karen forest. Floor-to-ceiling glass, wood-burning stone fireplace, outdoor cedar hot tub, and organic herb garden.',
    tagline: 'Indulgent Glass & Cedar Sanctuary in Historic Karen',
    photos: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
    ],
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ['Cedar Wood Hot Tub', 'Wood Fireplace', 'Curated Wine Cellar', 'Fast Fiber WiFi', 'Smart Security & Guard'],
    pricePerNightKES: 38000,
    pricePerNightUSD: 295,
    ownerName: 'Dr. Alistair Ross',
    ownerPhone: '+254733902111',
    active: true,
    featured: true,
    badge: 'Nairobi VIP Escape',
  },
  {
    id: 'stay-watamu-marine',
    title: 'Watamu Blue Horizon Eco-Villa',
    slug: 'watamu-blue-horizon-villa',
    location: 'Watamu Marine National Park, Kilifi',
    region: 'Coast',
    description: 'Perched on high coral cliffs above Watamu’s turquoise bay, this open-air villa blends Makuti thatch with high-end Italian design. Panoramic sunrise deck, direct private steps down to the marine reserve beach.',
    tagline: 'Cliff-Edge Luxury Overlooking Coral Marine Sanctuary',
    photos: [
      'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80',
    ],
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    amenities: ['Private Marine Access', 'Saltwater Pool', 'Swahili Seafood Chef', 'Stand Up Paddleboards', 'Generator Backup'],
    pricePerNightKES: 45000,
    pricePerNightUSD: 350,
    ownerName: 'Guido Moretti',
    ownerPhone: '+254705334120',
    active: true,
    featured: false,
    badge: 'Marine View',
  },
  {
    id: 'stay-mara-river-suite',
    title: 'Mara Cliffside Safari Suite & Tent Pavilion',
    slug: 'mara-cliffside-safari-suite',
    location: 'Mara North Conservancy, Maasai Mara',
    region: 'Safari / Mara',
    description: 'Ultra-exclusive private bush villa on the rim of Mara North Conservancy. Includes private customized 4x4 open safari vehicle with gold-level Maasai guide, private plunge pool looking out onto wildlife waterhole.',
    tagline: 'Private Conservancy Bush Estate with Dedicated Game Vehicle',
    photos: [
      'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80',
    ],
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    amenities: ['Private 4x4 Land Cruiser & Guide', 'Waterhole View Plunge Pool', 'All-Inclusive Gourmet Dining', 'Bush Sundowners', 'Solar & Starlink'],
    pricePerNightKES: 120000,
    pricePerNightUSD: 930,
    ownerName: 'Ole Saitoti & Safari Partners',
    ownerPhone: '+254728551980',
    active: true,
    featured: true,
    badge: 'Exclusive Safari',
  }
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Wanjiku Mugo',
    email: 'wanjiku.mugo@kenya-executives.co.ke',
    phone: '+254722123456',
    vipTier: 'vip',
    notes: 'Managing Partner at corporate law firm. Always prefers morning flights, aisle seat, and private chef at Diani stays.',
    createdAt: '2026-06-10T08:30:00Z',
  },
  {
    id: 'client-2',
    name: 'Marcus & Elena Vance',
    email: 'marcus.vance@techventures.co.uk',
    phone: '+254718990112',
    vipTier: 'ultra_vip',
    notes: 'Expat tech executives based in Nairobi. Request round-trip Wilson flights with champagne on arrival.',
    createdAt: '2026-07-02T14:15:00Z',
  },
  {
    id: 'client-3',
    name: 'Hon. Kevin Ochieng',
    email: 'k.ochieng@energyholdings.ke',
    phone: '+254733445566',
    vipTier: 'vip',
    notes: 'Frequent business and weekend leisure traveler. Prefers Jambojet / Kenya Airways for Mombasa routes.',
    createdAt: '2026-08-01T11:00:00Z',
  },
];

export const INITIAL_BOOKINGS: BookingRequest[] = [
  {
    id: 'req-ken-8492',
    trackingCode: 'KEN-8492X',
    clientId: 'client-1',
    client: INITIAL_CLIENTS[0],
    bookingType: 'flight_and_bnb',
    flightRouteId: 'route-wil-uka',
    flightOrigin: 'Nairobi Wilson (WIL)',
    flightDestination: 'Diani Beach / Ukunda (UKA)',
    flightDate: '2026-08-28',
    flightReturnDate: '2026-08-31',
    flightIsRoundTrip: true,
    flightPax: 2,
    flightPreferredTime: 'morning',
    flightCarrierPreference: 'Safarilink',
    bnbListingId: 'stay-diani-sultan',
    bnbCheckIn: '2026-08-28',
    bnbCheckOut: '2026-08-31',
    bnbGuests: 2,
    bnbBudgetTier: 'Ultra-Luxury VIP',
    vipAirportTransfer: true,
    privateChefRequest: true,
    champagneOnArrival: true,
    specialRequests: 'Celebrating 10th anniversary. Please ensure chilled Moët & Chandon upon arrival at the villa.',
    status: 'quoted',
    quote: {
      id: 'quote-8492',
      flightPriceKES: 54000, // 2 pax roundtrip Wilson -> Ukunda
      bnbPriceKES: 195000, // 3 nights @ 65,000 KES
      conciergeFeeKES: 15000,
      totalPriceKES: 264000,
      totalPriceUSD: 2045,
      quotedAirline: 'Safarilink Dash 8 (Dep 09:30 AM / Ret 16:00 PM)',
      quotedStayName: 'Sultan Sands Oceanfront Villa (3 Nights)',
      quoteNotes: 'Confirmed 2x Return seats on Safarilink flight 031/032 + exclusive use of Sultan Sands Villa with Chef Tariq and anniversary champagne arrangement.',
      validUntil: '2026-08-25T18:00:00Z',
      sentAt: '2026-08-19T08:00:00Z',
    },
    adminNotes: 'Called Safarilink reservations desk (Seats locked under PNR QX981 for 48h). Spoke with Capt Tariq for villa availability. Client is VIP.',
    createdAt: '2026-08-18T16:20:00Z',
    updatedAt: '2026-08-19T08:00:00Z',
  },
  {
    id: 'req-ken-9104',
    trackingCode: 'KEN-9104M',
    clientId: 'client-2',
    client: INITIAL_CLIENTS[1],
    bookingType: 'flight_and_bnb',
    flightRouteId: 'route-wil-lau',
    flightOrigin: 'Nairobi Wilson (WIL)',
    flightDestination: 'Lamu Island (LAU)',
    flightDate: '2026-09-04',
    flightReturnDate: '2026-09-08',
    flightIsRoundTrip: true,
    flightPax: 4,
    flightPreferredTime: 'afternoon',
    flightCarrierPreference: 'Skyward Express',
    bnbListingId: 'stay-lamu-shela-palace',
    bnbCheckIn: '2026-09-04',
    bnbCheckOut: '2026-09-08',
    bnbGuests: 4,
    bnbBudgetTier: 'Ultra-Luxury VIP',
    vipAirportTransfer: true,
    privateChefRequest: true,
    champagneOnArrival: false,
    specialRequests: 'Need a motorized Swahili dhow transfer directly from Manda airstrip jetty to Shela House.',
    status: 'confirmed',
    quote: {
      id: 'quote-9104',
      flightPriceKES: 132000,
      bnbPriceKES: 340000, // 4 nights @ 85,000 KES
      conciergeFeeKES: 25000,
      totalPriceKES: 497000,
      totalPriceUSD: 3850,
      quotedAirline: 'Skyward Express (Wilson 14:00 -> Lamu Manda)',
      quotedStayName: 'Forodhani Swahili House (4 Nights Full Staff)',
      quoteNotes: 'Full package with private Dhow captain and 4 nights exclusive beachfront estate.',
      validUntil: '2026-08-16T18:00:00Z',
      sentAt: '2026-08-15T10:00:00Z',
    },
    payment: {
      method: 'mpesa',
      status: 'completed',
      mpesaReceipt: 'QJD8912K89',
      mpesaPhone: '+254718990112',
      paidAt: '2026-08-15T11:45:00Z',
      amountKES: 497000,
      amountUSD: 3850,
    },
    itinerary: {
      airlineBookingRef: 'SW-LAMU-8921',
      flightDetailsSummary: 'Skyward Express Flight OW-204, Departs Wilson Airport (WIL) Terminal 2 at 14:00 on Sept 4. Return Flight OW-205 Departs Manda (LAU) 16:30 on Sept 8. 20kg checked luggage included.',
      baggageAllowance: '20kg checked + 5kg cabin per passenger',
      departureTerminal: 'Wilson Airport, Skyward Lounge Terminal',
      stayConfirmationRef: 'FORODHANI-VIP-770',
      stayAddress: 'Beachfront Plot 14, Shela Village, Lamu Island',
      checkInInstructions: 'Captain Ahmed will meet you at Manda jetty holding a sign with your name. Private Dhow transfer takes 10 mins to Shela house steps.',
      hostContactPhone: '+254711456789 (Fatma Bwana)',
      conciergeLeadName: 'Jerry (Head Concierge)',
      conciergeLeadPhone: '+254700000000',
      confirmedAt: '2026-08-15T12:00:00Z',
    },
    adminNotes: 'M-Pesa payment received in full. Safaricom receipt verified. Airline tickets issued via portal. House staff briefed.',
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-15T12:00:00Z',
  },
  {
    id: 'req-ken-3301',
    trackingCode: 'KEN-3301P',
    clientId: 'client-3',
    client: INITIAL_CLIENTS[2],
    bookingType: 'flight_only',
    flightRouteId: 'route-nbo-mba',
    flightOrigin: 'Nairobi JKIA (NBO)',
    flightDestination: 'Mombasa (MBA)',
    flightDate: '2026-09-12',
    flightReturnDate: '2026-09-14',
    flightIsRoundTrip: true,
    flightPax: 1,
    flightPreferredTime: 'morning',
    flightCarrierPreference: 'Kenya Airways',
    vipAirportTransfer: true,
    specialRequests: 'Prefer early morning 06:30 AM flight KQ 602. Business class if available.',
    status: 'pending_review',
    adminNotes: 'New request from Hon. Kevin. Need to check KQ Business availability for Sept 12.',
    createdAt: '2026-08-19T07:30:00Z',
    updatedAt: '2026-08-19T07:30:00Z',
  }
];
